#!/bin/bash

# =============================================================================
# sync-claude-rules.sh
#
# This script concatenates all Cursor rules from .cursor/rules/*.mdc
# into a single CLAUDE.md file for Claude Code compatibility.
#
# Usage: npm run sync:claude-rules
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
RULES_DIR="$PROJECT_ROOT/.cursor/rules"
OUTPUT_FILE="$PROJECT_ROOT/CLAUDE.md"

# Check if rules directory exists
if [ ! -d "$RULES_DIR" ]; then
    echo "Error: Rules directory not found at $RULES_DIR"
    exit 1
fi

# Check if there are any .mdc files
if ! ls "$RULES_DIR"/*.mdc 1> /dev/null 2>&1; then
    echo "Error: No .mdc files found in $RULES_DIR"
    exit 1
fi

# Create CLAUDE.md with warning header
cat > "$OUTPUT_FILE" << 'EOF'
<!--
╔═══════════════════════════════════════════════════════════════════════════════╗
║                                                                               ║
║   ⚠️  WARNING: DO NOT EDIT THIS FILE MANUALLY ⚠️                               ║
║                                                                               ║
║   This file is auto-generated from .cursor/rules/*.mdc files.                 ║
║   Any manual changes will be overwritten on the next sync.                    ║
║                                                                               ║
║   To update coding rules:                                                     ║
║   1. Edit the appropriate file in .cursor/rules/                              ║
║   2. Run: npm run sync:claude-rules                                           ║
║                                                                               ║
║   See README.md for more information.                                         ║
║                                                                               ║
╚═══════════════════════════════════════════════════════════════════════════════╝
-->

# Coding Rules for Claude Code

This file contains the coding standards and conventions for this project.
These rules are automatically synced from `.cursor/rules/` directory.

---

EOF

# Concatenate all .mdc files
for file in "$RULES_DIR"/*.mdc; do
    if [ -f "$file" ]; then
        filename=$(basename "$file")
        echo "Processing: $filename"

        # Add file separator
        echo "" >> "$OUTPUT_FILE"
        echo "<!-- Source: .cursor/rules/$filename -->" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"

        # Append file content (skip frontmatter metadata for cleaner output)
        # The frontmatter is between --- markers at the start
        awk '
            BEGIN { in_frontmatter = 0; frontmatter_done = 0 }
            /^---$/ && !frontmatter_done {
                in_frontmatter = !in_frontmatter
                if (!in_frontmatter) frontmatter_done = 1
                next
            }
            !in_frontmatter && frontmatter_done { print }
        ' "$file" >> "$OUTPUT_FILE"

        echo "" >> "$OUTPUT_FILE"
        echo "---" >> "$OUTPUT_FILE"
    fi
done

echo ""
echo "✅ Successfully synced rules to $OUTPUT_FILE"
echo "   Source: $RULES_DIR/*.mdc"
